version: '2.1'

services:
  rabbitmq:
    build:
      context: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
      - 15674:15674

  worker:
    build:
      context: worker
    links:
      - rabbitmq

  mon:
    build:
      context: web
    links:
      - rabbitmq
    ports:
      - 8080:8080
