version: '2.1'

services:
  rabbitmq:
    build:
      context: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
      - 15674:15674

  mq2:
    build:
      context: rabbitmq
    ports:
      - 5673:5672
      - 15673:15672
      - 15675:15674
    links:
      - rabbitmq

  worker:
    build:
      context: worker
    links:
      - rabbitmq

  mon:
    build:
      context: web
    links:
      - mq2
    ports:
      - 8080:8080
