---
- hosts: all
  gather_facts: false
  vars:
    rabbitmq_url: http://guest:guest@localhost:15672
    inspection_exchange_name: celery_inspection
    rabbitmq_vhost: "%2f" # urlencoded '/'

    src_exchange_name: celery
    src_queue_name: celery
    src_queue_routing_key: celery
  tasks:
    - name: Delete shovel config
      uri:
        url: "{{ rabbitmq_url }}/api/parameters/shovel/{{ rabbitmq_vhost }}/shovel_{{ inspection_exchange_name }}"
        method: DELETE
      register: delete_shovel_request
      failed_when: delete_shovel_request.status not in (204, 404)

    - name: Delete Exchange
      rabbitmq_exchange:
        name: "{{ inspection_exchange_name }}"
        type: fanout
        state: absent
