---
- hosts: all
  gather_facts: false
  vars_files:
    - config.yml

  tasks:
    - name: Worker MQ - Delete shovel config
      uri:
        url: "{{ worker_amqp.url }}/api/parameters/shovel/{{ worker_amqp.vhost }}/shovel_{{ worker_amqp.shovel_exchange_name }}"
        method: DELETE
      register: delete_shovel_request
      changed_when: delete_shovel_request.status == 204
      failed_when: delete_shovel_request.status not in (204, 404)

    - name: Worker MQ - Delete Exchange
      rabbitmq_exchange:
        name: "{{ worker_amqp.shovel_exchange_name }}"
        login_port: 15672
        type: fanout
        state: absent

    - name: External MQ - Delete shovel config
      uri:
        url: "{{ external_amqp.url }}/api/parameters/shovel/{{ external_amqp.vhost }}/shovel_{{ external_amqp.shovel_exchange_name }}"
        method: DELETE
      register: delete_shovel_request
      changed_when: delete_shovel_request.status == 204
      failed_when: delete_shovel_request.status not in (204, 404)

    - name: External MQ - Delete Exchange
      rabbitmq_exchange:
        name: "{{ external_amqp.shovel_exchange_name }}"
        login_port: 15673
        type: fanout
        state: absent
